[[rules]]
description = "Ignore placeholder password in DATABASE_URI"
regex = '''DATABASE_URI=mongodb://root:<your-database-password>@mongodb'''

[[rules]]
description = "Ignore placeholder REFRESH_TOKEN_SECRET"
regex = '''REFRESH_TOKEN_SECRET=<your-refresh-token-secret>'''

[[rules]]
description = "Ignore placeholder ACCESS_TOKEN_SECRET"
regex = '''ACCESS_TOKEN_SECRET=<your-access-token-secret>'''

[[rules]]
description = "Ignore placeholder Mongo root password"
regex = '''MONGO_INITDB_ROOT_PASSWORD=<your-database-password>'''
