name: Scan, Build and Push Docker Images
on:
  workflow_dispatch:
  push:
    branches: 
      - main
    paths:
      - "FRONTEND/**"
      - "BACKEND/**"
  pull_request:
    branches: 
      - main
    paths:
      - "FRONTEND/**"
      - "BACKEND/**"

jobs:
  security-checks:
    name: Security Checks
    runs-on: ubuntu-latest
    env:
      continue: "false"
    strategy:
      matrix:
        service:
          - name: frontend
            path: FRONTEND
          - name: backend
            path: BACKEND

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check if source changed
        run: |
          if git diff --quiet HEAD^ HEAD -- ${{ matrix.service.path }}; then
            echo "continue=false" >> $GITHUB_ENV
          else
            echo "continue=true" >> $GITHUB_ENV
          fi

      - name: Install Node
        if: env.continue == 'true'
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install Dependencies
        if: env.continue == 'true'
        working-directory: ${{ matrix.service.path }}
        run: npm install

      - name: Install Semgrep
        if: env.continue == 'true'
        run: pip install semgrep

      - name: SAST (Semgrep)
        if: env.continue == 'true'
        run: semgrep --config p/ci --include="${{ matrix.service.path }}/**/*.{ts,tsx,js,jsx}" --exclude='**/node_modules/**' --exclude='**/dist/**' --exclude='**/build/**'

      - name: SCA (npm audit)
        if: env.continue == 'true'
        working-directory: ${{ matrix.service.path }}
        run: npm audit --audit-level=high

      - name: Install Gitleaks
        if: env.continue == 'true'
        run: |
          curl -LO https://github.com/gitleaks/gitleaks/releases/download/v8.20.1/gitleaks_8.20.1_linux_x64.tar.gz
          tar -zxvf gitleaks_8.20.1_linux_x64.tar.gz
          sudo mv gitleaks /usr/local/bin/

      - name: Run Gitleaks
        if: env.continue == 'true'
        working-directory: ${{ matrix.service.path }}
        run: gitleaks detect --source . --exit-code 1

  docker-build-push:
    needs: security-checks
    name: Docker Build & Push
    runs-on: ubuntu-latest
    env:
      continue: "false"
    strategy:
      matrix:
        service:
          - name: "davidlihor/stacknotes-app"
            path: "FRONTEND"
          - name: "davidlihor/stacknotes-svc"
            path: "BACKEND"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Check Changes
        run: |
          if git diff --quiet HEAD^ HEAD -- ${{matrix.service.path}}; then
            echo "continue=false" >> $GITHUB_ENV
          else 
            echo "continue=true" >> $GITHUB_ENV
          fi

      - name: Set up Docker Buildx
        if: env.continue == 'true'
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        if: env.continue == 'true'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push
        if: env.continue == 'true'
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{matrix.service.path}}/Dockerfile
          push: true
          tags: ${{matrix.service.name}}:gh-${{ github.sha }}