name: Build and Push Docker Images

on:
  workflow_dispatch:
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      continue: "false"
    strategy:
      matrix:
        service:
          - name: "davidlihor/stacknotes-app"
            path: "FRONTEND"
          - name: "davidlihor/stacknotes-svc"
            path: "BACKEND"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Check Changes
        run: |
          if git diff --quiet HEAD^ HEAD -- ${{matrix.service.path}}; then
            echo "continue=false" >> $GITHUB_ENV
          else 
            echo "continue=true" >> $GITHUB_ENV
          fi

      - name: Set up Docker Buildx
        if: env.continue == 'true'
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        if: env.continue == 'true'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push
        if: env.continue == 'true'
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{matrix.service.path}}/Dockerfile
          push: true
          tags: ${{matrix.service.name}}:gh-${{ github.sha }}